# Generated by Django 6.0.5 on 2026-06-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_sale_productsale'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsale',
            name='price',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='productsale',
            name='quantity',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
